// {
//   "items": [
//     { "menuItemId": "pm", "name": "Paneer Masala", "price": 140 },
//     { "menuItemId": "pmm", "name": "Paneer Mirch Masala", "price": 150 },
//     { "menuItemId": "pbm", "name": "Paneer Butter Masala", "price": 190 },
//     { "menuItemId": "ptm", "name": "Paneer Tikka Masala", "price": 200 },
//     { "menuItemId": "pk", "name": "Paneer Kadai", "price": 180 },
//     { "menuItemId": "ph", "name": "Paneer Handi", "price": 180 },
//     { "menuItemId": "pbc", "name": "Paneer Bhurji Curry", "price": 160 },
//     { "menuItemId": "ph2", "name": "Paneer Hingwadi", "price": 180 },
//     { "menuItemId": "ppt", "name": "Paneer Patiala", "price": 180 },
//     { "menuItemId": "pph", "name": "Paneer Pahanda", "price": 180 },
//     { "menuItemId": "pa", "name": "Paneer Angara", "price": 180 },
//     { "menuItemId": "p-msh", "name": "Paneer Mashaal", "price": 180 },
//     { "menuItemId": "p-mhr", "name": "Paneer Maharaja", "price": 180 },
//     { "menuItemId": "pvd", "name": "Paneer Viddi Dupbar (Do Pyaza)", "price": 180 },
//     { "menuItemId": "pmz", "name": "Paneer Mumtaz", "price": 180 },
//     { "menuItemId": "sp", "name": "Shahi Paneer", "price": 180 },
//     { "menuItemId": "mp", "name": "Matter Paneer", "price": 180 },
//     { "menuItemId": "pp", "name": "Palak Paneer", "price": 180 },
//     { "menuItemId": "ch-btrm", "name": "Cheese Butter Masala", "price": 200 },
//     { "menuItemId": "pdp", "name": "Paneer Do Pyazza", "price": 190 },
//     { "menuItemId": "pd", "name": "Plain Dal", "price": 100 },
//     { "menuItemId": "df", "name": "Dal Fry", "price": 100 },
//     { "menuItemId": "jd", "name": "Jeera Dal", "price": 100 },
//     { "menuItemId": "bdf", "name": "Butter Dal Fry", "price": 120 },
//     { "menuItemId": "dt", "name": "Dal Tadka", "price": 120 },
//     { "menuItemId": "bdt", "name": "Butter Dal Tadka", "price": 130 },
//     { "menuItemId": "dk", "name": "Dal Kolhapuri", "price": 130 },
//     { "menuItemId": "dmra", "name": "Dal Maharaja", "price": 140 },
//     { "menuItemId": "dmri", "name": "Dal Maharani", "price": 140 },
//     { "menuItemId": "dp", "name": "Dal Palak", "price": 120 },
//     { "menuItemId": "br", "name": "Boondi Raita", "price": 40 },
//     { "menuItemId": "cr", "name": "Cucumber Raita", "price": 40 },
//     { "menuItemId": "gr", "name": "Green Salad", "price": 30 },
//     { "menuItemId": "ks", "name": "Kachumber Salad", "price": 25 },
//     { "menuItemId": "ts", "name": "Tomato Salad", "price": 25 },
//     { "menuItemId": "mks", "name": "Mula Koshimbir", "price": 20 },
//     { "menuItemId": "ck", "name": "Cabbage Koshimbir", "price": 25 },
//     { "menuItemId": "rg", "name": "Rasgulla", "price": 80 },
//     { "menuItemId": "gj", "name": "Gulab Jamun", "price": 80 },
//     { "menuItemId": "sk", "name": "Shrikhand", "price": 80 },
//     { "menuItemId": "rp", "name": "Roasted Papad", "price": 12 },
//     { "menuItemId": "fp", "name": "Fried Papad", "price": 20 },
//     { "menuItemId": "mp2", "name": "Masala Papad", "price": 25 },
//     { "menuItemId": "rmp", "name": "Roasted Masala Papad", "price": 30 },
//     { "menuItemId": "nfp", "name": "Nagali Fried Papad", "price": 30 },
//     { "menuItemId": "nmp", "name": "Nagali Masala Papad", "price": 35 },
//     { "menuItemId": "tr", "name": "Tandoori Roti (Plain)", "price": 15 },
//     { "menuItemId": "trb", "name": "Tandoori Roti Butter", "price": 20 },
//     { "menuItemId": "pn", "name": "Plain Naan", "price": 30 },
//     { "menuItemId": "bn", "name": "Butter Naan", "price": 50 },
//     { "menuItemId": "gn", "name": "Garlic Naan", "price": 50 },
//     { "menuItemId": "pr", "name": "Paratha", "price": 25 },
//     { "menuItemId": "jr", "name": "Jowar Roti", "price": 25 },
//     { "menuItemId": "br2", "name": "Bajra Roti", "price": 25 },
//     { "menuItemId": "jrb", "name": "Jowar Roti Butter", "price": 30 },
//     { "menuItemId": "brb", "name": "Bajra Roti Butter", "price": 30 },
//     { "menuItemId": "blp", "name": "Butter Lachha Paratha", "price": 35 },
//     { "menuItemId": "sr", "name": "Steam Rice", "price": 90 },
//     { "menuItemId": "jr2", "name": "Jeera Rice", "price": 100 },
//     { "menuItemId": "mr", "name": "Masala Rice", "price": 120 },
//     { "menuItemId": "dk2", "name": "Dal Khichdi", "price": 130 },
//     { "menuItemId": "bdr", "name": "Butter Dal Khichdi", "price": 140 },
//     { "menuItemId": "tdr", "name": "Tadka Dal Khichdi", "price": 150 },
//     { "menuItemId": "vp", "name": "Veg Pulao", "price": 150 },
//     { "menuItemId": "vb", "name": "Veg Biryani", "price": 150 },
//     { "menuItemId": "hb", "name": "Hyderabadi Biryani", "price": 160 },
//     { "menuItemId": "vfr", "name": "Veg Fried Rice", "price": 130 },
//     { "menuItemId": "mfr", "name": "Manchurian Fried Rice", "price": 150 },
//     { "menuItemId": "sfr", "name": "Schezwan Fried Rice", "price": 140 },
//     { "menuItemId": "vman", "name": "Veg Manchurian (Dry/Gravy)", "price": 140 },
//     { "menuItemId": "pc", "name": "Paneer Chilly (Dry/Gravy)", "price": 160 },
//     { "menuItemId": "p65", "name": "Paneer 65", "price": 160 },
//     { "menuItemId": "pman", "name": "Paneer Manchurian", "price": 160 },
//     { "menuItemId": "vc", "name": "Veg Crispy", "price": 140 },
//     { "menuItemId": "pc2", "name": "Paneer Crispy", "price": 160 },
//     { "menuItemId": "sc", "name": "Soya Chilly", "price": 160 },
//     { "menuItemId": "mc", "name": "Mushroom Chilly", "price": 120 },
//     { "menuItemId": "cc", "name": "Chana Chilly", "price": 120 },
//     { "menuItemId": "vhn", "name": "Veg Hakka Noodles", "price": 120 },
//     { "menuItemId": "sn", "name": "Schezwan Noodles", "price": 120 },
//     { "menuItemId": "mn", "name": "Manchurian Noodles", "price": 150 },
//     { "menuItemId": "am", "name": "Aloo Mutter", "price": 120 },
//     { "menuItemId": "ag", "name": "Aloo Gobi", "price": 120 },
//     { "menuItemId": "at", "name": "Aloo Tomato", "price": 120 },
//     { "menuItemId": "aj", "name": "Aloo Jeera", "price": 120 },
//     { "menuItemId": "cm", "name": "Chana Masala", "price": 120 },
//     { "menuItemId": "gps", "name": "Green Peas Masala", "price": 120 },
//     { "menuItemId": "bm", "name": "Bhendi Masala", "price": 120 },
//     { "menuItemId": "bf", "name": "Bhendi Fry", "price": 130 },
//     { "menuItemId": "bb", "name": "Baingan Bharta", "price": 130 },
//     { "menuItemId": "sb", "name": "Sev Bhaji", "price": 130 },
//     { "menuItemId": "st", "name": "Sev Tomato", "price": 130 },
//     { "menuItemId": "mv", "name": "Mix Veg", "price": 130 },
//     { "menuItemId": "vmr", "name": "Veg Maharaja", "price": 140 },
//     { "menuItemId": "vp2", "name": "Veg Patiala", "price": 140 },
//     { "menuItemId": "vb2", "name": "Veg Bharata", "price": 140 },
//     { "menuItemId": "vk", "name": "Veg Korma", "price": 140 },
//     { "menuItemId": "vmm", "name": "Veg Malai Methi", "price": 140 },
//     { "menuItemId": "vki", "name": "Veg Keema", "price": 140 },
//     { "menuItemId": "vk2", "name": "Veg Kolhapuri", "price": 140 },
//     { "menuItemId": "sm", "name": "Soya Masala", "price": 120 },
//     { "menuItemId": "sc2", "name": "Soya Curry", "price": 120 },
//     { "menuItemId": "va", "name": "Veg Angara", "price": 150 },
//     { "menuItemId": "vb3", "name": "Veg Bhuna", "price": 140 },
//     { "menuItemId": "vh", "name": "Veg Haryali", "price": 130 },
//     { "menuItemId": "vs", "name": "Veg Shimla", "price": 130 },
//     { "menuItemId": "vt", "name": "Veg Tomato", "price": 130 },
//     { "menuItemId": "va2", "name": "Veg Aloo", "price": 130 },
//     { "menuItemId": "lp", "name": "Lasooni Palak", "price": 120 },
//     { "menuItemId": "kc", "name": "Kaju Curry", "price": 140 },
//     { "menuItemId": "km", "name": "Kaju Masala", "price": 130 },
//     { "menuItemId": "ks2", "name": "Kaju Shingapuri", "price": 130 },
//     { "menuItemId": "mpm", "name": "Mushroom Paneer Masala", "price": 180 },
//     { "menuItemId": "kpm", "name": "Kaju Paneer Masala", "price": 170 },
//     { "menuItemId": "mc2", "name": "Mushroom Curry", "price": 140 },
//     { "menuItemId": "mk", "name": "Mushroom Kadhai", "price": 160 },
//     { "menuItemId": "mh", "name": "Mushroom Handi", "price": 160 },
//     { "menuItemId": "ma", "name": "Mushroom Angara", "price": 180 }
//   ]
// }
